<a href="https://colab.research.google.com/github/Ritesh-panda/NLP-Learnings/blob/main/LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
text="""The sun slowly dipped below the horizon,
painting the sky in shades of orange and purple as the city began to quiet down.
People walked along the streets,
some heading home after a long day of work while others gathered in small groups,
sharing stories and laughter. A gentle breeze moved through the trees,
carrying with it the scent of fresh rain from earlier in the evening.
In a small café on the corner, a writer sat by the window, typing steadily on a laptop,
trying to capture the fleeting emotions of the moment. The world outside seemed to pause,
just for a second,
as if giving space for thoughts to settle and dreams to form.
Somewhere in the distance, a train passed by, its sound fading into the night,
leaving behind a sense of calm and quiet anticipation for what tomorrow might bring."""

In [61]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import Tokenizer

In [62]:
#initiate teh tokenizer
tkn=Tokenizer()

In [63]:
tkn.fit_on_texts([text])

In [64]:
len(tkn.word_index)

101

In [65]:
for sentence in text.split('\n'):
  print(sentence)

The sun slowly dipped below the horizon, 
painting the sky in shades of orange and purple as the city began to quiet down.
People walked along the streets, 
some heading home after a long day of work while others gathered in small groups, 
sharing stories and laughter. A gentle breeze moved through the trees, 
carrying with it the scent of fresh rain from earlier in the evening. 
In a small café on the corner, a writer sat by the window, typing steadily on a laptop, 
trying to capture the fleeting emotions of the moment. The world outside seemed to pause, 
just for a second, 
as if giving space for thoughts to settle and dreams to form. 
Somewhere in the distance, a train passed by, its sound fading into the night, 
leaving behind a sense of calm and quiet anticipation for what tomorrow might bring.


In [66]:
for sentence in text.split('\n'):
  print(tkn.texts_to_sequences([sentence]))

[[1, 13, 14, 15, 16, 1, 17]]
[[18, 1, 19, 3, 20, 4, 21, 6, 22, 8, 1, 23, 24, 5, 9, 25]]
[[26, 27, 28, 1, 29]]
[[30, 31, 32, 33, 2, 34, 35, 4, 36, 37, 38, 39, 3, 10, 40]]
[[41, 42, 6, 43, 2, 44, 45, 46, 47, 1, 48]]
[[49, 50, 51, 1, 52, 4, 53, 54, 55, 56, 3, 1, 57]]
[[3, 2, 10, 58, 11, 1, 59, 2, 60, 61, 12, 1, 62, 63, 64, 11, 2, 65]]
[[66, 5, 67, 1, 68, 69, 4, 1, 70, 1, 71, 72, 73, 5, 74]]
[[75, 7, 2, 76]]
[[8, 77, 78, 79, 7, 80, 5, 81, 6, 82, 5, 83]]
[[84, 3, 1, 85, 2, 86, 87, 12, 88, 89, 90, 91, 1, 92]]
[[93, 94, 2, 95, 4, 96, 6, 9, 97, 7, 98, 99, 100, 101]]


In [67]:
input_seq=[]
for sentence in text.split('\n'):
  tkn_sentence=tkn.texts_to_sequences([sentence])

  for i in range(1, len(tkn_sentence[0])):
    input_seq.append(tkn_sentence[0][:i+1])
input_seq

[[1, 13],
 [1, 13, 14],
 [1, 13, 14, 15],
 [1, 13, 14, 15, 16],
 [1, 13, 14, 15, 16, 1],
 [1, 13, 14, 15, 16, 1, 17],
 [18, 1],
 [18, 1, 19],
 [18, 1, 19, 3],
 [18, 1, 19, 3, 20],
 [18, 1, 19, 3, 20, 4],
 [18, 1, 19, 3, 20, 4, 21],
 [18, 1, 19, 3, 20, 4, 21, 6],
 [18, 1, 19, 3, 20, 4, 21, 6, 22],
 [18, 1, 19, 3, 20, 4, 21, 6, 22, 8],
 [18, 1, 19, 3, 20, 4, 21, 6, 22, 8, 1],
 [18, 1, 19, 3, 20, 4, 21, 6, 22, 8, 1, 23],
 [18, 1, 19, 3, 20, 4, 21, 6, 22, 8, 1, 23, 24],
 [18, 1, 19, 3, 20, 4, 21, 6, 22, 8, 1, 23, 24, 5],
 [18, 1, 19, 3, 20, 4, 21, 6, 22, 8, 1, 23, 24, 5, 9],
 [18, 1, 19, 3, 20, 4, 21, 6, 22, 8, 1, 23, 24, 5, 9, 25],
 [26, 27],
 [26, 27, 28],
 [26, 27, 28, 1],
 [26, 27, 28, 1, 29],
 [30, 31],
 [30, 31, 32],
 [30, 31, 32, 33],
 [30, 31, 32, 33, 2],
 [30, 31, 32, 33, 2, 34],
 [30, 31, 32, 33, 2, 34, 35],
 [30, 31, 32, 33, 2, 34, 35, 4],
 [30, 31, 32, 33, 2, 34, 35, 4, 36],
 [30, 31, 32, 33, 2, 34, 35, 4, 36, 37],
 [30, 31, 32, 33, 2, 34, 35, 4, 36, 37, 38],
 [30, 31, 32, 33, 

In [68]:
#these numbers are not in the same dimensions so due to which we have to add the zero pading
#which will help in getting the dimension same
#zero padding:- 0 in back and front
#get the larget line
max_len=max([len(x) for x in input_seq])
max_len

18

In [69]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded=pad_sequences(input_seq, maxlen=max_len, padding='pre')
padded

array([[  0,   0,   0, ...,   0,   1,  13],
       [  0,   0,   0, ...,   1,  13,  14],
       [  0,   0,   0, ...,  13,  14,  15],
       ...,
       [  0,   0,   0, ...,   7,  98,  99],
       [  0,   0,   0, ...,  98,  99, 100],
       [  0,   0,   0, ...,  99, 100, 101]], dtype=int32)

In [70]:
#so in the pad seq the last will be y and the first will be x
x=padded[:,:-1]
y=padded[:,-1]

In [71]:
x

array([[  0,   0,   0, ...,   0,   0,   1],
       [  0,   0,   0, ...,   0,   1,  13],
       [  0,   0,   0, ...,   1,  13,  14],
       ...,
       [  0,   0,   0, ...,  97,   7,  98],
       [  0,   0,   0, ...,   7,  98,  99],
       [  0,   0,   0, ...,  98,  99, 100]], dtype=int32)

In [72]:
y

array([ 13,  14,  15,  16,   1,  17,   1,  19,   3,  20,   4,  21,   6,
        22,   8,   1,  23,  24,   5,   9,  25,  27,  28,   1,  29,  31,
        32,  33,   2,  34,  35,   4,  36,  37,  38,  39,   3,  10,  40,
        42,   6,  43,   2,  44,  45,  46,  47,   1,  48,  50,  51,   1,
        52,   4,  53,  54,  55,  56,   3,   1,  57,   2,  10,  58,  11,
         1,  59,   2,  60,  61,  12,   1,  62,  63,  64,  11,   2,  65,
         5,  67,   1,  68,  69,   4,   1,  70,   1,  71,  72,  73,   5,
        74,   7,   2,  76,  77,  78,  79,   7,  80,   5,  81,   6,  82,
         5,  83,   3,   1,  85,   2,  86,  87,  12,  88,  89,  90,  91,
         1,  92,  94,   2,  95,   4,  96,   6,   9,  97,   7,  98,  99,
       100, 101], dtype=int32)

In [73]:
#we now have our input and output
#it is a classifcation-multiple so one hot encoding
tkn.word_index

{'the': 1,
 'a': 2,
 'in': 3,
 'of': 4,
 'to': 5,
 'and': 6,
 'for': 7,
 'as': 8,
 'quiet': 9,
 'small': 10,
 'on': 11,
 'by': 12,
 'sun': 13,
 'slowly': 14,
 'dipped': 15,
 'below': 16,
 'horizon': 17,
 'painting': 18,
 'sky': 19,
 'shades': 20,
 'orange': 21,
 'purple': 22,
 'city': 23,
 'began': 24,
 'down': 25,
 'people': 26,
 'walked': 27,
 'along': 28,
 'streets': 29,
 'some': 30,
 'heading': 31,
 'home': 32,
 'after': 33,
 'long': 34,
 'day': 35,
 'work': 36,
 'while': 37,
 'others': 38,
 'gathered': 39,
 'groups': 40,
 'sharing': 41,
 'stories': 42,
 'laughter': 43,
 'gentle': 44,
 'breeze': 45,
 'moved': 46,
 'through': 47,
 'trees': 48,
 'carrying': 49,
 'with': 50,
 'it': 51,
 'scent': 52,
 'fresh': 53,
 'rain': 54,
 'from': 55,
 'earlier': 56,
 'evening': 57,
 'café': 58,
 'corner': 59,
 'writer': 60,
 'sat': 61,
 'window': 62,
 'typing': 63,
 'steadily': 64,
 'laptop': 65,
 'trying': 66,
 'capture': 67,
 'fleeting': 68,
 'emotions': 69,
 'moment': 70,
 'world': 71,
 'outsi

In [74]:
from tensorflow.keras.utils import to_categorical
to_categorical(y, num_classes=102)#+1 always


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [75]:
y.shape

(132,)

In [76]:
x.shape

(132, 17)

###Model building

In [77]:
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [93]:
model=Sequential()
model.add(Embedding(102, 100, input_length=max_len-1))#x.shape will be going inside
model.add(LSTM(150))#100 is a hyperparameter and the dimensions of all the ct ft zt will be 100
model.add(Dense(102, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [94]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [95]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [96]:
model.build(input_shape=(None, x.shape[1])) # Build the model explicitly
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 17, 100)        │        10,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 102)            │        15,402 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 176,202 (688.29 KB)

 Trainable params: 176,202 (688.29 KB)

 Non-trainable params: 0 (0.00 B)

Here's a breakdown of the parameters for each layer:

*   **Embedding Layer**: This layer converts word indices into dense vectors. The number of parameters is calculated as `vocabulary_size * embedding_dimension`.
    *   `vocabulary_size` is 102 (from `num_classes` in `Embedding(102, 100, ...)`).
    *   `embedding_dimension` is 100.
    *   Parameters: `102 * 100 = 10,200`

*   **LSTM Layer**: The parameters for an LSTM layer with `units` are calculated as `4 * ((input_dim + units) * units + units)`.
    *   `input_dim` here is the `embedding_dimension` from the previous layer, which is 100.
    *   `units` for the LSTM layer is 100.
    *   Parameters: `4 * ((100 + 100) * 100 + 100) = 4 * (200 * 100 + 100) = 4 * 20,100 = 80,400`

*   **Dense Layer**: This is a standard fully connected layer. The number of parameters is `input_dim * units + units` (for biases).
    *   `input_dim` here is the number of units from the LSTM layer, which is 100.
    *   `units` for the Dense layer is 102.
    *   Parameters: `100 * 102 + 102 = 10,200 + 102 = 10,302`

**Total parameters**: `10,200 (Embedding) + 80,400 (LSTM) + 10,302 (Dense) = 100,902`.

In [97]:
x.shape

(132, 17)

In [98]:
y.shape

(132,)

In [99]:
model.fit(x, to_categorical(y, num_classes=102), epochs=100)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - accuracy: 0.0758 - loss: 4.6218
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.1061 - loss: 4.5823
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.1061 - loss: 4.4568
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.1061 - loss: 4.3279
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.1061 - loss: 4.2781
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.1061 - loss: 4.2409
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.1061 - loss: 4.2216
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.1061 - loss: 4.1976
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.1061 - loss: 4.1984
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.1061 - loss: 4.1806
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.1061 - loss: 4.1686
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.1061 - lo

###TEXT THE MODEL

In [89]:
txt2="painting"
#tokenization
tkn_txt2=tkn.texts_to_sequences(txt2)
#padding
padded_txt=pad_sequences(tkn_txt2, maxlen=max_len-1, padding='pre')
#model prediction
model.predict(padded_txt)



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step


array([[7.12557885e-05, 5.73789068e-02, 3.84907387e-02, 1.37315169e-02,
        1.03782420e-03, 3.68640907e-02, 7.75600411e-03, 8.14763308e-02,
        2.28598466e-04, 1.21856872e-04, 7.04757310e-03, 2.00753752e-02,
        4.80102259e-04, 3.58985178e-02, 1.04508651e-02, 4.01779730e-03,
        2.15970422e-03, 3.17791273e-04, 4.57757087e-05, 1.41372364e-02,
        1.51261536e-03, 1.04615501e-04, 1.45675513e-04, 5.66837625e-05,
        2.33362865e-04, 3.16803416e-05, 1.44695019e-04, 6.21442348e-02,
        2.88965423e-02, 2.74759275e-03, 5.60348926e-05, 1.33282915e-01,
        3.99217680e-02, 1.60546880e-02, 1.61192520e-03, 1.11136155e-03,
        4.27341583e-04, 2.41855771e-04, 1.19136617e-04, 6.07302973e-05,
        3.47490859e-04, 4.29095126e-05, 3.94339934e-02, 2.93548731e-03,
        3.61012644e-04, 1.11203699e-03, 3.30984883e-04, 5.44306298e-04,
        3.43331281e-04, 4.31051558e-05, 1.31905422e-01, 2.52123307e-02,
        3.06224893e-03, 3.92964896e-04, 1.78800736e-04, 7.718841

In [86]:
import numpy as np

In [87]:
pos=np.argmax(model.predict(padded_txt))
pos

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


np.int64(31)

In [88]:
for word, index in tkn.word_index.items():
  if index==pos:
    print(word)

heading


In [92]:
txt3="The sun slowly"
#tokenization
tkn_txt2=tkn.texts_to_sequences(txt3)
#padding
padded_txt3=pad_sequences(tkn_txt2, maxlen=max_len-1, padding='pre')
#model prediction
model.predict(padded_txt3)
pos3=np.argmax(model.predict(padded_txt3))
for word, index in tkn.word_index.items():
  if index==pos3:
    print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
heading


## Using Pre-trained GloVe Embeddings to Improve Accuracy

First, let's download the pre-trained GloVe embeddings. We'll use a relatively small version (50-dimensional vectors, trained on Wikipedia 2014 + Gigaword 5 corpus) to keep the download and processing time manageable for this example.

In [100]:
import os
import zipfile
import requests

# URL for GloVe embeddings (50d, Wikipedia 2014 + Gigaword 5)
glove_url = "http://nlp.stanford.edu/data/glove.6B.zip"
glove_zip_path = "glove.6B.zip"
glove_dir = "glove.6B"

# Download the zip file if it doesn't exist
if not os.path.exists(glove_zip_path):
    print(f"Downloading {glove_url}...")
    response = requests.get(glove_url, stream=True)
    with open(glove_zip_path, "wb") as f:
        for chunk in response.iter_content(chunk_size=8192):
            f.write(chunk)
    print("Download complete.")

# Unzip the file if the directory doesn't exist
if not os.path.exists(glove_dir):
    print(f"Unzipping {glove_zip_path}...")
    with zipfile.ZipFile(glove_zip_path, 'r') as zip_ref:
        zip_ref.extractall(glove_dir)
    print("Unzipping complete.")

print(f"GloVe embeddings are in: {glove_dir}")

Download complete.
Unzipping glove.6B.zip...
Unzipping complete.
GloVe embeddings are in: glove.6B


In [101]:
embeddings_index = {}
f = open(os.path.join(glove_dir, 'glove.6B.50d.txt'))
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()
print(f'Found {len(embeddings_index)} word vectors.')

Found 400000 word vectors.


In [102]:
embedding_dim = 50 # GloVe 50-dimensional vectors
vocab_size = len(tkn.word_index) + 1 # +1 for 0-padding in Keras Embedding layer
embedding_matrix = np.zeros((vocab_size, embedding_dim))

for word, i in tkn.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        # Words not found in embedding index will be all-zeros.
        embedding_matrix[i] = embedding_vector
print(f'Shape of embedding matrix: {embedding_matrix.shape}')

Shape of embedding matrix: (102, 50)


\Now, we will recreate the model, but this time we'll initialize the `Embedding` layer with the `embedding_matrix` we just created. We'll also set `trainable=False` for the embedding layer, which means these pre-trained weights will not be updated during our training process. This is a common practice when using pre-trained embeddings with small datasets to prevent them from being distorted.

In [103]:
model_glove = Sequential()
model_glove.add(Embedding(vocab_size, # Use vocab_size from embedding_matrix

                          embedding_dim, # Use embedding_dim from GloVe
                          weights=[embedding_matrix], # Initialize with pre-trained weights
                          input_length=max_len-1,
                          trainable=False)) # Set to False for fine-tuning
model_glove.add(LSTM(100))
model_glove.add(Dense(vocab_size, activation='softmax')) # Use vocab_size for output

model_glove.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model_glove.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │         5,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,100 (19.92 KB)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 5,100 (19.92 KB)

In [104]:
model_glove.fit(x, to_categorical(y, num_classes=vocab_size), epochs=100)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - accuracy: 0.0152 - loss: 4.6354   
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.0909 - loss: 4.5281
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1061 - loss: 4.4509
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1061 - loss: 4.3754
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1061 - loss: 4.3027
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.1061 - loss: 4.2264
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.1061 - loss: 4.1532    
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.1061 - loss: 4.0851
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.1061 - loss: 4.0148
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1061 - loss: 3.9413
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1288 - loss: 3.8861
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.11